nameOverride: ''
fullnameOverride: ''
imageRepository: eqalpha/keydb
imageTag: x86_64_v6.3.2
imagePullPolicy: IfNotPresent
imagePullSecrets: []
nodes: 3
password: ''
existingSecret: ''
existingSecretPasswordKey: password
port: 6379
portName: server
internalPort: 6379
internalPortName: keydb
threads: 2
multiMaster: 'yes'
activeReplicas: 'yes'
protectedMode: 'no'
appendonly: 'no'
annotations: {}
configExtraArgs:
- storage-provider:
  - flash
  - /data/flash
- enable-async-commands:
  - 'yes'
- soft-shutdown:
  - 'yes'
persistence:
  enabled: true
  mountPath: /data/flash
  size: 20Gi
podAnnotations: {}
tolerations: {}
nodeSelector: {}
topologySpreadConstraints: []
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - '{{ include "keydb.name" . }}'
          - key: app.kubernetes.io/instance
            operator: In
            values:
            - '{{ .Release.Name }}'
        topologyKey: kubernetes.io/hostname
additionalAffinities: {}
podDisruptionBudget:
  enabled: true
  maxUnavailable: 1
extraInitContainers: []
extraContainers: []
extraVolumes: []
livenessProbe:
  enabled: true
  custom: {}
  initialDelaySeconds: 20
  periodSeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
readinessProbe:
  enabled: true
  custom: {}
  initialDelaySeconds: 20
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 5
readinessProbeRandomUuid: 90f717dd-0e68-43b8-9363-fddaad00d6c9
startupProbe:
  enabled: true
  custom: {}
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 24
lifecycle: {}
persistentVolume:
  enabled: true
  accessModes:
  - ReadWriteOnce
  selector: {}
  size: 1Gi
  emptyDir: {}
resources: {}
securityContext: {}
keydb:
  securityContext: {}
service:
  annotations: {}
  appProtocol:
    enabled: false
serviceAccount:
  enabled: false
  create: true
  name: ''
  extraSpec: {}
loadBalancer:
  enabled: false
  annotations: {}
  extraSpec: {}
serviceMonitor:
  enabled: false
  labels: null
  annotations: null
  interval: 30s
exporter:
  enabled: false
  imageRepository: oliver006/redis_exporter
  imageTag: v1.48.0-alpine
  pullPolicy: IfNotPresent
  port: 9121
  portName: redis-exporter
  scrapePath: /metrics
  livenessProbe:
    httpGet:
      path: /health
      port: redis-exporter
  readinessProbe:
    httpGet:
      path: /health
      port: redis-exporter
  startupProbe:
    httpGet:
      path: /health
      port: redis-exporter
    failureThreshold: 24
    periodSeconds: 5
  resources: {}
  securityContext: {}
  extraArgs: []
scripts:
  enabled: false
  resources: {}
  securityContext: {}
  cleanupCoredumps:
    enabled: false
    minutes: 1440
  cleanupTempfiles:
    enabled: true
    minutes: 60
