apiVersion: v1
kind: ConfigMap
metadata:
  name: webdis
  namespace: keydb-flash-test
  annotations:
    argocd.argoproj.io/sync-wave: "3"
data:
  webdis.json: |
    {
      "redis_host": "keydb-flash.keydb-flash-test.svc.cluster.local",
      "redis_port": 6379,
      "redis_auth": null,

      "http_host": "0.0.0.0",
      "http_port": 7379,

      "threads": 5,
      "pool_size": 20,

      "daemonize": false,
      "websockets": false,

      "database": 0,

      "acl": [
        { "disabled": ["DEBUG"] },
        { "http_basic_auth": "user:password", "enabled": ["*"] }
      ],

      "verbosity": 4,
      "logfile": "/dev/stderr"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdis
  namespace: keydb-flash-test
  labels:
    app: webdis
    name: webdis
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: Replace=true   # مهم علشان مشكلة immutable selector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webdis
      name: webdis
  template:
    metadata:
      name: webdis
      labels:
        app: webdis
        name: webdis
    spec:
      nodeSelector:
         cloud.google.com/gke-nodepool: "app-nodes"
     # tolerations:
     # - key: "persist-dbs"
      #  operator: "Equal"
       # value: "true"
        #effect: "NoExecute"
      volumes:
      - name: config
        configMap:
          name: webdis
          items:
          - key: webdis.json
            path: webdis.json
      containers:
      - name: webdis
        image: nicolas/webdis:latest
        imagePullPolicy: Always
        command: ["/usr/local/bin/webdis","/config/webdis.json"]
        ports:
        - containerPort: 7379
        volumeMounts:
        - mountPath: /config
          name: config
---
apiVersion: v1
kind: Service
metadata:
  name: webdissvc
  namespace: keydb-flash-test
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  type: ClusterIP
  selector:
    name: webdis
  ports:
  - name: http
    port: 6380
    targetPort: 7379
    protocol: TCP
